#!/bin/bash
# ==============================================================================
# Lab 3 — Splunk SIEM: RDP Exposure Remediation
# ==============================================================================
# Restricts vm-actived's RDP rule (NSG "RDP" in RG-ACTIVED/vm-actived-nsg) to a
# single trusted IP. This rule had sourceAddressPrefix "*" — opened during the
# first manual attempt at this lab (July 2) and never closed — leaving RDP open
# to the entire internet for several days. Splunk's own SIEM pipeline caught
# 4,500+ failed-login (EventCode 4625) events generated by automated internet
# scanning before this was found and fixed. See NOTES.md for the full incident
# timeline and verification steps (EventCode=4624 confirming no successful
# unauthorized logins occurred).
#
# Usage: bash 04-lockdown-rdp.sh [optional: IP to allow, defaults to your current IP]
# ==============================================================================
set -euo pipefail

LAB1_RG="RG-ACTIVED"
NSG_NAME="vm-actived-nsg"
RULE_NAME="RDP"

ALLOWED_IP="${1:-$(curl -4 -s ifconfig.me)}"
echo "==> Restricting RDP access to: $ALLOWED_IP"

echo "==> Current rule state (before):"
az network nsg rule show \
  --resource-group "$LAB1_RG" \
  --nsg-name "$NSG_NAME" \
  --name "$RULE_NAME" \
  --query "{name:name, sourceAddressPrefix:sourceAddressPrefix, destinationPortRange:destinationPortRange}" \
  -o table

echo "==> Updating rule to restrict source to $ALLOWED_IP..."
az network nsg rule update \
  --resource-group "$LAB1_RG" \
  --nsg-name "$NSG_NAME" \
  --name "$RULE_NAME" \
  --source-address-prefixes "$ALLOWED_IP"

echo "==> Confirmed rule state (after):"
az network nsg rule show \
  --resource-group "$LAB1_RG" \
  --nsg-name "$NSG_NAME" \
  --name "$RULE_NAME" \
  --query "{name:name, sourceAddressPrefix:sourceAddressPrefix, destinationPortRange:destinationPortRange}" \
  -o table

echo ""
echo "==> Done. RDP (3389) on vm-actived is now reachable only from $ALLOWED_IP."
echo "==> Re-run this script any time your IP changes (dynamic home IPs shift periodically)."
